using Microsoft.AspNetCore.Mvc;

namespace training_net.Controllers
{
    public class HelloWorldController : Controller
    {
        public IActionResult Index()
        {
            ViewData["firstTitle"] = "This title was generated by the CONTROLLER";
            ViewData["firstParagraph"] = "...and this paragraph too...";
            return View();
        }
    }
}
